baseurl: /starter
permalink: pretty
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
maptime:
  chapter: Maptime Southampton
  twitter: @MaptimeSOTON
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
